#!/bin/sh

daemon="/etc/ru1/ru1-wrapper"
daemon_flags=""
daemon_user=_ru1

. /etc/rc.d/rc.subr

pexp="${daemon}.*"
rc_bg=YES
rc_reload=NO

rc_start() {
        ${rcexec} "${daemon} ${daemon_flags} < /dev/null 2>&1 | \
                logger -p daemon.info -t ru1"
}

rc_cmd $1
